#!/usr/bin/perl

use Digest::SHA1 qw(sha1_hex);
use Sys::Hostname;
use strict;
use warnings;

# Seed the random number generator with the hostname of this box so that
# we get a consistent random number.  We want to run the registration at a
# consistent time on each individual box, but randomize the runs across
# the environment.
srand(hex(substr(sha1_hex(hostname), 0, 7)));

# Cron job is set to run every 3 hours
my $MAX_SLEEP = 60 * 60 * 3;

sleep(int(rand($MAX_SLEEP)));

exec '/usr/bin/nv', '--register';

