#!/bin/sh

# Everything about this makes me feel dirty
crontab -l | grep -v nventory > /tmp/root_crontab || exit 1
echo "0 0,3,6,9,12,15,18,21 * * * /usr/sbin/nventory_cron_wrapper > /dev/null 2>&1" >> /tmp/root_crontab || exit 1
echo "0 0 * * * /opt/csw/bin/pkg-get -U > /dev/null 2>&1; /opt/csw/bin/pkg-get -u YPCnventory > /dev/null 2>&1" >> /tmp/root_crontab || exit 1
crontab /tmp/root_crontab
rm /tmp/root_crontab

# Run a one-time registration right away
nventory --register
